### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by emirhnkoc** [ucarbehlul/eksiarchiver#6]
```
node archiver.js "ssg"
https://eksisozluk.com/biri/ssg açılacak.
Sayfa yüklendi.
Entryler yükleniyor...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Evaluation failed: ReferenceError: $ is not defined
    at yukle (__puppeteer_evaluation_script__:4:18)
    at __puppeteer_evaluation_script__:20:12
    at ExecutionContext._evaluateInternal (C:\eksiarchiver\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\eksiarchiver\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at async C:\eksiarchiver\archiver.js:19:20
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\eksiarchiver\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\eksiarchiver\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  -- ASYNC --
    at Frame.<anonymous> (C:\eksiarchiver\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\eksiarchiver\node_modules\puppeteer\lib\Page.js:860:43)
    at Page.<anonymous> (C:\eksiarchiver\node_modules\puppeteer\lib\helper.js:112:23)
    at C:\eksiarchiver\archiver.js:19:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.0
```

**Comment by ucarbehlul** [comment]
Merhaba, sorunu bildirdiğiniz için teşekkürler. https://github.com/ucarbehlul/eksiarchiver/commit/2de5a31756aba619a4bd483901d26f584c0d8a46 ile çözülmüş olması lazım, lütfen tekrar deneyin.

**Comment by emirhnkoc** [comment]
Evet çözüldü teşekkürler.
